<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Start Of Execution(TEST)->Regression suite 1]]>
    </line>
    <line>
      <![CDATA[Test Started->testRealReportOne]]>
    </line>
    <line>
      <![CDATA[Test Pass->testRealReportOne]]>
    </line>
    <line>
      <![CDATA[Test Started->testRealReportTwo]]>
    </line>
    <line>
      <![CDATA[Test Failed->testRealReportTwo]]>
    </line>
    <line>
      <![CDATA[<a href=https://www.google.co.in/?gfe_rd=cr&ei=jE2tWLmIM_TI8Aed-aEg&gws_rd=ssl>click to open screenshot</a>]]>
    </line>
  </reporter-output>
  <suite name="example suite 1" duration-ms="298" started-at="2017-07-06T06:01:38Z" finished-at="2017-07-06T06:01:38Z">
    <groups>
    </groups>
    <test name="Regression suite 1" duration-ms="298" started-at="2017-07-06T06:01:38Z" finished-at="2017-07-06T06:01:38Z">
      <class name="tests.TG_ITestLisener_Test">
        <test-method status="PASS" signature="testRealReportOne()[pri:0, instance:tests.TG_ITestLisener_Test@548b7f67]" name="testRealReportOne" duration-ms="11" started-at="2017-07-06T11:31:38Z" finished-at="2017-07-06T11:31:38Z">
          <reporter-output>
            <line>
              <![CDATA[Test Started->testRealReportOne]]>
            </line>
            <line>
              <![CDATA[Test Pass->testRealReportOne]]>
            </line>
          </reporter-output>
        </test-method> <!-- testRealReportOne -->
        <test-method status="FAIL" signature="testRealReportTwo()[pri:0, instance:tests.TG_ITestLisener_Test@548b7f67]" name="testRealReportTwo" duration-ms="2" started-at="2017-07-06T11:31:38Z" finished-at="2017-07-06T11:31:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at tests.TG_ITestLisener_Test.testRealReportTwo(TG_ITestLisener_Test.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started->testRealReportTwo]]>
            </line>
            <line>
              <![CDATA[Test Failed->testRealReportTwo]]>
            </line>
            <line>
              <![CDATA[<a href=https://www.google.co.in/?gfe_rd=cr&ei=jE2tWLmIM_TI8Aed-aEg&gws_rd=ssl>click to open screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- testRealReportTwo -->
        <test-method status="SKIP" signature="testRealReportThree()[pri:0, instance:tests.TG_ITestLisener_Test@548b7f67]" name="testRealReportThree" duration-ms="0" started-at="2017-07-06T11:31:38Z" depends-on-methods="tests.TG_ITestLisener_Test.testRealReportTwo" finished-at="2017-07-06T11:31:38Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TG_ITestLisener_Test.testRealReportThree()[pri:0, instance:tests.TG_ITestLisener_Test@548b7f67] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TG_ITestLisener_Test.testRealReportThree()[pri:0, instance:tests.TG_ITestLisener_Test@548b7f67] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRealReportThree -->
      </class> <!-- tests.TG_ITestLisener_Test -->
    </test> <!-- Regression suite 1 -->
  </suite> <!-- example suite 1 -->
</testng-results>
